### ISSUE TITLE
Improve component styling now that css-grid is fully supported

### ISSUE THREAD

**Issue by jason-capsule42** [AlaskaAirlines/auro-pane#45]
### Please describe the bug

The component styles contains the following code:

```css
@supports (display: grid) {
      display: grid;

      grid-template-columns: auto;
      grid-template-rows: 1.625rem 1.25rem;
    }
```

This can be cleaned up using https://caniuse.com/css-grid

### Reproducing the error

None

### Exit criteria

CSS styles use css grid
